on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: "Build"

jobs:
  build-cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - windows-2019
          - macos-10.15

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install Dependencies (Linux)"
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev

      - name: "Install Dependencies (OSX)"
        if: ${{ runner.os == 'macOS' }}
        run: |
          brew install sdl2

      - name: "Compile"
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          cmake --install . --prefix wop

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: build/wop/
